server:
  port: 8881
connection-timeout: 18000000
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m(分钟)，s(秒)，h(小时)，不写单位默认毫秒
spring:
  application:
    name: TestPlatform
  profiles:
    active: dev
TestPlatform:
  key: TestPlatform



